### ISSUE TITLE
IDA commands authors

### ISSUE THREAD

**Issue by 0x00ach** [ANSSI-FR/polichombr#144]
Hi,

The commands pushed by Skelenox are displayed as authored by "Analyst" in the Web UI, even if the skelsettings "username" is set to another value.

Cheers,

**Comment by tpo-anssi** [comment]
Hi,
the username in skelsettings is not used and will be removed by #166.

However, the "Analyst" name was hardcoded, and is replaced by the used id as of #163 .

I hope that solves your problem.

++
