### ISSUE TITLE
Block multiple skelenox instances in IDA Pro

### ISSUE THREAD

**Issue by 0x00ach** [ANSSI-FR/polichombr#148]
Hi,

While patching skelenox.py, I did load it multiple times in my IDA Pro instance. All of the instances were actually "working" (i.e hooks receivinig notifications), which lead to several issues (multiple requests, connection error, etc.).

Skelenox should find existing instances and safely unload them (i.e remove hooks) in order to avoid such issues. In the main proc, just check for the "skel" object, and if it exists, call its "end_skelenox()" method, then overwrite it.

Cheers,

**Comment by 0x00ach** [comment]
Seems that multiple skelenox instances were present in the IDA Pro session (3 at least). 

A unload procedure might be useful in order to block such behaviors.

**Comment by tpo-anssi** [comment]
Hi 0x00, could you test with the patch included in #153 ?

**Comment by tpo-anssi** [comment]
Without an answer, I think this should be fixed, so I am closing the issue!

Thank you!
