### ISSUE TITLE
   TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by Neolex-Security** [ANSSI-FR/polichombr#16]
Bonjour lorsque je lance run.py j'ai ces erreurs : 

> ## neolex@archlinux> polichombr$./run.py 
> 
> INFO in analysis [/home/atlas/polichombr/app/controllers/analysis.py:29]:
> ## Loading tasks
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_yara : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_peinfo : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_analyzeitrb : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_strings : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> - Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
> ##  \* Restarting with stat
> 
> INFO in analysis [/home/atlas/polichombr/app/controllers/analysis.py:29]:
> ## Loading tasks
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_yara : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_peinfo : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_analyzeitrb : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> ---
> 
> ERROR in analysis [/home/atlas/polichombr/app/controllers/analysis.py:51]:
> ## Could not load task_strings : Parent module 'app.controllers.tasks' not loaded, cannot perform relative import
> - Debugger is active!
> - Debugger pin code: 132-071-423

`

Et lorsque je m'inscrit sur l'interface web : 
`builtins.TypeError

TypeError: Unicode-objects must be encoded before hashing
Traceback (most recent call last)

```
File "/usr/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__

return self.wsgi_app(environ, start_response)

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app

response = self.make_response(self.handle_exception(e))

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception

reraise(exc_type, exc_value, tb)

File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

raise value

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app

response = self.full_dispatch_request()

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise

raise value

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request

rv = self.dispatch_request()

File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/home/atlas/polichombr/app/views/webui.py", line 127, in register_user

registration_form.poke_id.data)

File "/home/atlas/polichombr/app/controllers/user.py", line 27, in create

apikey_seed = apikey_seed + sha256(username).hexdigest()

TypeError: Unicode-objects must be encoded before hashing
```

`

**Comment by HascoetKevin** [comment]
Je crois avoir reglé le soucis en ajoutant .encode('utf-8) après les objets a hasher : 
`        # TODO : manage API key with flask-login
        apikey_seed = str(random.randint(0, 0xFFFFFFFFFFFFFFFF))
        apikey_seed = apikey_seed + str(int(time.time()))
        apikey_seed = apikey_seed + sha256(username.encode('utf-8')).hexdigest()
        apikey_seed = apikey_seed + sha256(password.encode('utf-8')).hexdigest()
        apikey_seed = ''.join(random.sample(apikey_seed, len(apikey_seed)))
        myuser.api_key = sha256(apikey_seed.encode('utf-8')).hexdigest()`

**Comment by tpo-anssi** [comment]
According to your log, you are using Python 3, and (unfortunately) Polichombr is not currently
tested with Python 3. You should specify the 2.7 version of python when initializing your venv, and it should work

**Comment by HascoetKevin** [comment]
Ok should I help you upgrade Polichombr to python 3 ?
