### ISSUE TITLE
Dockerfile fails: cannot perform "mv db_create.py"

### ISSUE THREAD

**Issue by deadbits** [ANSSI-FR/polichombr#189]
When running `docker build -t polichombr .` I receive the following error:
```
Step 16/18 : RUN mv examples/db_create.py db_create.py
 ---> Running in 2d9ae2eb9cd4
mv: cannot stat 'examples/db_create.py': No such file or directory
The command '/bin/sh -c mv examples/db_create.py db_create.py' returned a non-zero code: 1
```

The example/db_create.py definitely exists and the steps look correct at first glance, so I'm not really sure what's going on here. WORKDIR is set correctly..

My branch is a fresh clone of the repo as seen below:
```
zeroharbor :: /opt/polichombr ‹dev› » git branch
* dev
zeroharbor :: /opt/polichombr ‹dev› » git remote -v
origin	https://github.com/ANSSI-FR/polichombr (fetch)
origin	https://github.com/ANSSI-FR/polichombr (push)
zeroharbor :: /opt/polichombr ‹dev› » git status
On branch dev
Your branch is up-to-date with 'origin/dev'.
nothing to commit, working directory clean
zeroharbor :: /opt/polichombr ‹dev› » ls examples
add_family.py  create_yara.py  db_migrate.py       import_idb.py           samples_graph.py              send_sample.py
api_auth.py    db_create.py    get_family_info.py  reschedule_analysis.py  schedule_samples_analysis.py  stats_machoc.py
```

**Comment by shellchocolat** [comment]
If you download the tar.gz file, you will see that the db_create.py is missing from examples folder but is present in utils folder.

So modify  your Dockerfile and remove the line:
`RUN mv examples/db_create.py db_create.py`

and add instead:
`RUN mv utils/db_create.py db_create.py`

And that's it:
`docker build -t polichombr .`

**Comment by deadbits** [comment]
Perfect thanks for the help! I'll close this out
