### ISSUE TITLE
Suggestion: support radare2 in addition to IDA

### ISSUE THREAD

**Issue by XVilka** [ANSSI-FR/polichombr#3]
E.g. [this file analysis_tools/disassfunc.rb](https://github.com/ANSSI-FR/polichombr/blob/master/analysis_tools/disassfunc.rb) could be done using [r2pipe.rb](https://github.com/radare/radare2-bindings/tree/master/r2pipe/ruby) and [radare2](https://github.com/radare/radare2).
So users wouldn't need to install IDA Pro to get this working.

**Comment by jacquieandmichel** [comment]
Yes, I got lots of errore when I launched the script like this:
python3 analysis_tools/disassfunc.rb

**Comment by tpourcelot** [comment]
As this file is based on the metasm framework ( https://github.com/jjyg/metasm ), it is completely independant of IDA Pro.
It is used to generate graphs for a visual disassembly in the web UI, so I don't think it's necessary
to add a radare2 dependency for this.
