### ISSUE TITLE
Docker start error

### ISSUE THREAD

**Issue by PAFsec** [ANSSI-FR/polichombr#53]
Hello,

First, thank you for your work.

I would like to warn you, that by following the **INSTALL_DOCKER.md** guidelines, the docker container starts sucessfully, but the database does not seem to be created. It is probably because of the commented lines at the end of the Dockerfile (probably for a good reason!)

Here is the the backtrace:

> File "/opt/polichombr/flask/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
> self.connection = self.__connect()
> File "/opt/polichombr/flask/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
> connection = self.__pool._invoke_creator(self)
> File "/opt/polichombr/flask/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
> return dialect.connect(*cargs, **cparams)
> File "/opt/polichombr/flask/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
> return self.dbapi.connect(*cargs, **cparams)
> OperationalError: (sqlite3.OperationalError) unable to open database file

Another problem is the fact that ./utils/db_create.py requires the module **poli** that is only locally referenced (out of the box) at the root folder.
Therefore, we get the error :

> Traceback (most recent call last):
>   File "./utils/db_create.py", line 2, in <module>
>     from poli import db
> ImportError: No module named poli

 Regards,

**Comment by tpo-anssi** [comment]
Hello,
Thank you for your feedback!

Could you checkout #54 and test your docker build with it?

In fact, the two lines from `Dockerfile` were commented for local testing,
as if the database is already initialized when you share it in the volume this might cause problems.

Concerning the reference of the `poli` module,
this should be temporarily fixed by exporting the `PYTHONPATH` env variable to use the directory were it is cloned.

Regards,

**Comment by PAFsec** [comment]
Hello !

That works perfectly ! Thanks !

A little suggestion would be to handle the  **exceptions.DatabaseAlreadyControlledError** eception so the docker can still start even if you already have a database set up.

Keep the good work ! :)

**Comment by tpo-anssi** [comment]
The new issue is affected in #60 

This issue is close by #54
