### ISSUE TITLE
importing several YARA rules

### ISSUE THREAD

**Issue by cedricpernet** [ANSSI-FR/polichombr#85]
Hello,

Is it possible to import several YARA rules at the same time ?

For what I see, it seems we have to import them one by one ...

Thanks !

**Comment by tpo-anssi** [comment]
No, it is unfortunately impossible at the moment.
However, you can use the API to send multiple yara rules with relative ease

**Comment by cedricpernet** [comment]
Thanks for the reply, I will do. Yet there are several threat analysts around who will not use the API and would only work with the UI, so I guess they might not use your tool if this kind of possibility is not available.

**Comment by tpo-anssi** [comment]
After testing, you can add a ruleset directly from the web interface (and the API),
so I'm closing this issue now.

Thank you for your report
