### ISSUE TITLE
Passing the tests : I have to add some "with poli.app.app_context():"

### ISSUE THREAD

**Issue by harfangeek** [ANSSI-FR/polichombr#93]
Good evening,

I just cloned the repository, and tried to pass the tests as described in "CONTRIBUTING.md". All tests fail, I have a "Working outside of application context." for each of them. The errors correspond to the calls to poli.db in the setUp and tearDown methods of tests_api.py and tests_webui.py. In order to successfully pass the tests I have to enclose the poli.db calls with a "with poli.app.app_context():".

See my comit: https://github.com/harfangeek/polichombr/commit/4367c88ca74d357497732f8a92fbbd74d9974500

Do you experiment this issue?

Thank you.

**Comment by tpo-anssi** [comment]
Hi,
Some builds (however not all of them) were failing due to this bug,
it should be fixed with commit 3ab0069728d46a156ddc3e168180527949eea664 .

**Comment by tpo-anssi** [comment]
Fixed with #99
